version: '3'

services:
  nginx:
    image: nginx:1.21.1
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - monitoring
  exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: exporter
    hostname: exporter
    ports:
      - 9113:9113
    networks:
      - monitoring
    links:
      - nginx:nginx
    command: -nginx.scrape-uri=http://nginx/basic_status
  prometheus:
    image: prom/prometheus:v2.29.1
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - monitoring
    links:
      - exporter:exporter
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:8.1.1
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    links:
      - prometheus:prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
